services:
  postgres:
    image: postgres:15
    container_name: bank-postgres
    environment:
      POSTGRES_DB: bank
      POSTGRES_USER: bank_user
      POSTGRES_PASSWORD: bank_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bank-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bank_user -d bank"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 40s

  pgadmin:
    image: dpage/pgadmin4
    container_name: bank-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bank.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - bank-network

volumes:
  postgres_data:

networks:
  bank-network:
    driver: bridge
